name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "0 2 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: amankitsingh/badge-readme@main
        with:       
          CREDLY_USER: <ankit-singh.b7d565f6> # optional, but default will use the same from github
